apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-platform.fullname" . }}
  labels:
    {{- include "hello-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-platform.selectorLabels" . | nindent 4 }}
